### ISSUE TITLE
Deploy in portainer.io

### ISSUE THREAD

**Issue by andreyqg** [eea/eea.docker.rsync#3]
HI!
I am working with portainer.io and I am trying to deploy a new container based on eeacms/rsync:latest image, CMD | sh and ENTRYPOINT | /docker-entrypoint.sh, but I am obtaining Status: Stopped for a few seconds with exit code 0

I think possibly this error is because container can't stablish running.

Do you have acknowledgment any additional command or env variable I need to create together with the container to deploy

**Comment by valentinab25** [comment]
Hello,

Can you give me the command you are using? To be able to run sh as CMD, you also need to enable tty and interactive `-it`, like this:

     docker run -it eeacms/rsync sh

Otherwise, the `sh` process will stop, closing the container with it.

**Comment by avoinea** [comment]
Also to have `sshd` running within container you'll need to run it with `server` as CMD. Otherwise just use `client` or `cat` (with `-it`):

`docker run -it --rm eeacms/rsync cat`
