### ISSUE TITLE
PasswordAuth not disabled

### ISSUE THREAD

**Issue by daef** [eea/eea.docker.rsync#8]
[docker-entrypoint.sh:10](https://github.com/eea/eea.docker.rsync/blob/master/docker-entrypoint.sh#L10) tries to disable password authentication, but fails because sshd_config contains whitespace+ between `#` and `P`

allowing for optional spaces fixes this:

    sed -i "s/#\s*PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config

**Comment by valentinab25** [comment]
Solved in https://github.com/eea/eea.docker.rsync/commit/b574c1f112663525dcc70937a67cc8e4fa200690
